FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# Install build tools required for node-gyp
RUN apk add --no-cache \
        curl \
        python3 \
        make \
        g++ \
    && ln -sf /usr/bin/python3 /usr/bin/python

FROM base AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM base AS prod-deps
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

FROM oven/bun:1-alpine

WORKDIR /app
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/static ./src/static
COPY package.json ./

EXPOSE 4000
EXPOSE 9229

CMD ["bun", "dist/index.js"]
