overrides:
  "graphql": "16.11.0"
onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@biomejs/biome"
  - esbuild
  - heapdump
  - sharp
ignoredBuiltDependencies:
  - core-js
  - esbuild
  - msgpackr-extract
  - protobufjs
