name: Deploy to egdata.app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger api.egdata.app Deployment
        run: |
          curl -X POST "${{ secrets.COOLIFY_DEPLOY_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_KEY }}" 