name: Deploy PR to egdata.app

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger api.egdata.app PR Deployment
        run: |
          curl -X POST "${{ secrets.COOLIFY_DEPLOY_URL }}&pr=${{ github.event.pull_request.number }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_KEY }}" 